// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv @types/node
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    // Use direct connection URL for migrations (port 5432)
    // Fall back to pooled connection if direct URL is not available
    url: process.env.DATABASE_URL_MIGRATE || process.env.DATABASE_URL,
  },
});
